.TH "tardis" 1 "April 2012" "1.0"
.SH NAME
tardis \- Command line time tracking application
.SH SYNOPSIS
tardis add <start> <end> <project> [<description>]
.br
tardis all
.br
tardis r[eport] [<date>]
.br
tardis r[eport] [<start-date>] [<end-date>]
.br
tardis b[ackup]
.br
tardis end <id> <end-date>

.SH DESCRIPTION
A program for tracking time ... like a Time Lord.
.PP
tardis has a set of functions that can be accessed in two different ways:

    * Directly from the command line

And coming soon ...

    * Interactively

.SH HOMEPAGE
.PP
The homepage for
.B tardis
on the internet is http://github.com/wlangstroth/tardis
.SH AUTHOR
.PP
The author is Will Langstroth <will@langstroth.com>

.SH BUGS
Please report them to the author.

.SH SEE ALSO
There should be something here.
