.TH "tardis" 7 "January 2013" "0.1.3"
.
.SH "NAME"
\fBtardis\fR \- Command line time tracking application\.
.
.SH "SYNOPSIS"
\fBtardis\fR command [options]
.
.SH "DESCRIPTION"
A program for tracking time ... like a Time Lord\.
.
.SH "ESSENTIAL COMMANDS"
For the full command list, see the COMMANDS section\.
.
.SH "COMMANDS"
.
.TP
\fBs[tart]\fR \fIproject\fR [\fIdescription\fR]
Start a new activity on a project\.
.
.IP
The \fIDescription\fR is optional\.
.
.TP
\fBstop\fR
Stop the last activity\.
.
.TP
\fBadd\fR \fIstart\fR \fIend\fR \fIproject\fR [\fIdescription\fR]
Manually add an entry\.
.
.IP
Allows you to insert an entry into the entries table without having to go into sqlite.
.
.TP
\fBr[eport]\fR [\fIdate\fR]
Report on the day's time\.
.
.TP
\fBr[eport]\fR [\fIstart-date\fR] [\fIend-date\fR]
Report on the time spent between two dates\.
.
.TP
\fBb[ackup]\fR
Backup the current database in the ~/.tardis directory, using today's date as the file name.
.
.br
\fBtardis\fR end <id> <end-date>
.SH "HOMEPAGE"
.PP
The homepage for \fBtardis\fR on the internet is http://github.com/wlangstroth/tardis
.
.SH "AUTHOR"
.PP
The author is Will Langstroth <will@langstroth.com>
.
.SH BUGS
Please report them to the author.

